### ISSUE TITLE
How to get ckeditor instance

### ISSUE THREAD

**Issue by piernik** [lemonde/angular-ckeditor#14]
How to get ckeditor instance in my controller? I want to definde my custom blur event.

**Comment by shri2015** [comment]
q

**Comment by shri2015** [comment]
using ckeditor in ng-repeat and CKEDITOR.intsnaces it showing only one instance ,but in DOM it showing multiple div control for ckeditor instance

**Comment by Yvem** [comment]
Hello ! I updated the readme following encountering the same problem : https://github.com/lemonde/angular-ckeditor#getting-internal-ckeditor-instance
