### ISSUE TITLE
duplicated destory using ckeditor inside modal

### ISSUE THREAD

**Issue by xyuanX** [lemonde/angular-ckeditor#17]
greater wrapper for angular users, but I noticed that there is one issue using ckeditor inside the bootstrap $modal.

the issue can be seen when you close/dismiss the modal window, I guess the issue is because of duplicated destroy. so I change a little bit to avoid it, not very sure this is an good approach.

    // Destroy editor when the scope is destroyed.
    $scope.$on('$destroy', function onDestroy() {
      if(this.instance) {
        instance.destroy(false);      
      }
    });

**Comment by Yvem** [comment]
Hello,

can you elaborate a little about the error ? Does the latest fix (https://github.com/lemonde/angular-ckeditor/pull/20) solves your problem by any chance ?

**Comment by xyuanX** [comment]
@Yvem , yes exactly, #20 fix my issue, I will close this issue, thx
