### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by davetheflashguy** [lemonde/angular-ckeditor#31]
Hello,

I am trying to do an npm install but it seems like behind the scenes it's trying to do a bower install.  I am a little confused at what is happening.  This is the error message I am getting.  Any guidance or clarification would be appreciated.

c:\temp\>npm i angular-ckeditor
npm WARN package.json cbankerTest@1.0.0 No repository field.
npm WARN package.json cbankerTest@1.0.0 No README data
npm WARN package.json cbankerTest@1.0.0 No license field.
\
> angular-ckeditor@0.3.1 install c:\temp\cbankerTest\node_modules\angular-ckedit
or
> bower install

'bower' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "angular-ckeditor"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! angular-ckeditor@0.3.1 install: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-ckeditor@0.3.1 install script 'bower install'.
npm ERR! This is most likely a problem with the angular-ckeditor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-ckeditor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\temp\cbankerTest\npm-debug.log

**Comment by umeshv** [comment]
**Well the npm i angular-ckeditor fails for me as well, with the following error**

npm ERR! Failed at the angular-ckeditor@0.3.1 install script 'bower install'.
npm ERR! This is most likely a problem with the angular-ckeditor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-ckeditor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by Yvem** [comment]
`'bower' is not recognized as an internal or external command,`
