### ISSUE TITLE
Add angular-ckeditor to NPM

### ISSUE THREAD

**Issue by AmitMY** [lemonde/angular-ckeditor#45]
Please add angular-ckeditor to NPM

**Comment by Kesymaru** [comment]
I think the npm is already created, i do not know if this is the official npm but it looks to be the same github username @lemonde

https://www.npmjs.com/package/angular-ckeditor

Also the documentation does not mention the npm installation option.

**Comment by AmitMY** [comment]
Oh I did not find it.
I see it, but npm says:
"Whoops, should we have 'angular-ckeditor'?"

Probably because it is just version 0.3 and not 1.0.3

**Comment by simonv3** [comment]
Yeah, can someone bump this on NPM?

**Comment by travist** [comment]
Could the maintainers please run ```npm publish``` on this repo? It is pulling in version 0.3.

**Comment by jacek-pulit** [comment]
Hey @AmitMY version in npm is still 0.3.1. Are you able to publish new version 1.0.3 ?

**Comment by AmitMY** [comment]
@jacek-pulit I am not a collaborator on it. https://www.npmjs.com/package/angular-ckeditor
@lemonde @jbustin @offirmo @icandivideby0 are.
