### ISSUE TITLE
About NPM release

### ISSUE THREAD

**Issue by pvnr0082t** [lemonde/angular-ckeditor#54]
Hi @Yvem @mariusbrn ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We want to host this library.
I'd like to confirm that if https://www.npmjs.com/package/angular-ckeditor officially maintained or not. If yes, could you please synchronize the version between GitHub and NPM? I found that it's `v1.0.3` on GitHub but `v0.3.1` on NPM.
Thank you.

https://github.com/cdnjs/cdnjs/issues/9184

**Comment by xmj** [comment]
Any news?

**Comment by pvnr0082t** [comment]
`angular-ckeditor` has already been hosted on CDNJS. https://cdnjs.com/libraries/angular-ckeditor
