### ISSUE TITLE
Basicstyles + paragraph combobox not working in inline editing mode with multiple instances of ckeditor

### ISSUE THREAD

**Issue by coolduebtn** [lemonde/angular-ckeditor#59]
Hi,
I have multiple instances of ckeditor in the same page in inline editing mode.
In the first editor the basicstyles + paragraph are working correctly.
But from the 2nd editor onwards the combobox for basicstyles and paragraph are not shown onclicking.
Any help would be really appreciated.

Thanks

**Comment by ChandraKantPaliwal** [comment]
I am also face same issue in ckeditor math plugins it is working only in first instance. so let us know if you have solution
