### ISSUE TITLE
CKEDITOR not defined

### ISSUE THREAD

**Issue by msnpr567** [lemonde/angular-ckeditor#8]
i have included ckedior directive in my project with bower install angular-ckeditor . im getting CKEDITOR not defined error in console. can you help me?

**Comment by Yvem** [comment]
Hello !

As stated in the doc :
> Note : obviously this plugin expects the presence of AngularJS and CKEditor.

Did you also `bower install ckeditor` and loaded its js ? (manually or with a loader)

**Comment by msnpr567** [comment]
i have installed only angular-ckedior . i didnt install ckeditor . what else i have to install to get view.

**Comment by msnpr567** [comment]
if i placed ckeditor.js  its working fine. but when i build through grunt script in my sails projects. its not identifying ckeditor.js path.how can i solve this problem.

**Comment by ipsitam** [comment]
Any answers to this? Even i am facing this issue. Can anyone suggest how to get it fixed?

**Comment by Yvem** [comment]
Hello,

is CKEditor properly included in your build script ? We use minifications here at lemonde and it works fine.

Did you start from a template project or did you do it from scratch ?

**Comment by ipsitam** [comment]
Hey.. I am doing it from scratch. I had included the things properly. But its giving me errors when CKEditor is instantiated.

**Comment by ipsitam** [comment]
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/ckeditor/config.js?t=DAEB"
config.js?t=DAEB
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/ckeditor/skins/moono/editor_gecko.css?t=DAEB"
editor_...?t=DAEB
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/ckeditor/lang/en.js?t=DAEB"
en.js?t=DAEB
TypeError: this[b] is undefined
	

...ITOR.getUrl("lang/"+b+".js"),function(){this[b].dir=this.rtl[b]?"rtl":"ltr";a(b,...

**Comment by Yvem** [comment]
If you're having a 404, then it should be fixed first for this module to work.

**Comment by ipsitam** [comment]
Its fixed. Its searching for config.js . Its failing there.

**Comment by ipsitam** [comment]
Its saying config.js cannot be found.

**Comment by ipsitam** [comment]
Module is working ; and ckeditor is just a part of the field in my application.

**Comment by Yvem** [comment]
I close this issue, this is not related to angular-ckeditor but rather to the local webpage loading procedure.
